components/admin/config/routes.rb
Admin::Engine.routes.draw do
  namespace :manager do
    resources :admins
    resources :sponsors



  end


end

Account::Engine.routes.draw do
  devise_for :admins, module: 'devise', class_name: "Account::Admin", only: :sessions
end

components/admin/app/models/admin/application_record.rb
module Admin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

components/admin/app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
  end
end

components/admin/app/controllers/admin/manager/admins_controller.rb
require_dependency "admin/application_controller"
# TODO: not begin to edit.
module Admin
  class Manager::AdminsController < Admin::Manager::ApplicationController
    before_action :set_manager_admin, only: [:show, :edit, :update, :destroy]

    # GET /manager/admins
    def index
      @manager_admins = Manager::Admin.all
    end

    # GET /manager/admins/1
    def show
    end

    # GET /manager/admins/new
    def new
      @manager_admin = Manager::Admin.new
    end

    # GET /manager/admins/1/edit
    def edit
    end

    # POST /manager/admins
    def create
      @manager_admin = Manager::Admin.new(manager_admin_params)

      if @manager_admin.save
        redirect_to @manager_admin, notice: 'Admin was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /manager/admins/1
    def update
      if @manager_admin.update(manager_admin_params)
        redirect_to @manager_admin, notice: 'Admin was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /manager/admins/1
    def destroy
      @manager_admin.destroy
      redirect_to manager_admins_url, notice: 'Admin was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_manager_admin
        @manager_admin = Manager::Admin.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def manager_admin_params
        params.fetch(:manager_admin, {})
      end
  end
end

components/admin/app/controllers/admin/manager/application_controller.rb
module Admin
  class Manager::ApplicationController < ::Admin::ApplicationController

    before_action :authenticate_admin!

    # before_action :store_location, :only => [:edit]


    private

      def store_location
        session[:return_to] = request.referer if request.get? and controller_name != "user_sessions" and controller_name != "sessions"
      end

      def redirect_back_or_default(default, *args)
        redirect_to(session.delete(:return_to) || default, *args)
      end

  end
end

components/admin/app/controllers/admin/manager/sponsors_controller.rb
require_dependency "admin/application_controller"

module Admin
  class Manager::SponsorsController < Admin::Manager::ApplicationController
    # before_action :set_manager_sponsor, only: [:show, :edit, :update, :destroy]

    # GET /manager/sponsors
    def index
      # @manager_sponsors = Manager::Sponsor.all
    end

    # GET /manager/sponsors/1
    def show
    end

    # GET /manager/sponsors/new
    def new
      @manager_sponsor = Manager::Sponsor.new
    end

    # GET /manager/sponsors/1/edit
    def edit
    end

    # POST /manager/sponsors
    def create
      @manager_sponsor = Manager::Sponsor.new(manager_sponsor_params)

      if @manager_sponsor.save
        redirect_to @manager_sponsor, notice: 'Sponsor was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /manager/sponsors/1
    def update
      if @manager_sponsor.update(manager_sponsor_params)
        redirect_to @manager_sponsor, notice: 'Sponsor was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /manager/sponsors/1
    def destroy
      @manager_sponsor.destroy
      redirect_to manager_sponsors_url, notice: 'Sponsor was successfully destroyed.'
    end

    private

      # Only allow a list of trusted parameters through.
      def manager_sponsor_params
        params.fetch(:manager_sponsor, {})
      end
  end
end

components/admin/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
  end
end

components/admin/app/helpers/admin/manager/admins_helper.rb
module Admin
  module Manager::AdminsHelper
  end
end

components/admin/app/helpers/admin/manager/sponsors_helper.rb
module Admin
  module Manager::SponsorsHelper
  end
end

components/admin/app/views/admin/manager/admins/_form.html.erb
<%= form_with(model: manager_admin) do |form| %>
  <% if manager_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager_admin.errors.count, "error") %> prohibited this manager_admin from being saved:</h2>

      <ul>
        <% manager_admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

components/admin/app/views/admin/manager/admins/edit.html.erb
<h1>Editing Manager Admin</h1>

<%= render 'form', manager_admin: @manager_admin %>

<%= link_to 'Show', @manager_admin %> |
<%= link_to 'Back', manager_admins_path %>

components/admin/app/views/admin/manager/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manager Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manager_admins.each do |manager_admin| %>
      <tr>
        <td><%= link_to 'Show', manager_admin %></td>
        <td><%= link_to 'Edit', edit_manager_admin_path(manager_admin) %></td>
        <td><%= link_to 'Destroy', manager_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager Admin', new_manager_admin_path %>

components/admin/app/views/admin/manager/admins/new.html.erb
<h1>New Manager Admin</h1>

<%= render 'form', manager_admin: @manager_admin %>

<%= link_to 'Back', manager_admins_path %>

components/admin/app/views/admin/manager/admins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_manager_admin_path(@manager_admin) %> |
<%= link_to 'Back', manager_admins_path %>

components/admin/app/views/admin/manager/sponsors/_form.html.erb
<%= form_with(model: manager_sponsor) do |form| %>
  <% if manager_sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager_sponsor.errors.count, "error") %> prohibited this manager_sponsor from being saved:</h2>

      <ul>
        <% manager_sponsor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

components/admin/app/views/admin/manager/sponsors/edit.html.erb
<h1>Editing Manager Sponsor</h1>

<%= render 'form', manager_sponsor: @manager_sponsor %>

<%= link_to 'Show', @manager_sponsor %> |
<%= link_to 'Back', manager_sponsors_path %>

components/admin/app/views/admin/manager/sponsors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manager Sponsors</h1>



<%# link_to 'New Manager Sponsor', new_manager_sponsor_path %>

components/admin/app/views/admin/manager/sponsors/new.html.erb
<h1>New Manager Sponsor</h1>

<%= render 'form', manager_sponsor: @manager_sponsor %>

<%= link_to 'Back', manager_sponsors_path %>

components/admin/app/views/admin/manager/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_manager_sponsor_path(@manager_sponsor) %> |
<%= link_to 'Back', manager_sponsors_path %>

components/admin/app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# stylesheet_link_tag    "admin/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>